In [2]:
!pip install numpy

In [3]:
import numpy as np
list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [4]:
arr2 = np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [5]:
arr3 = np.zeros((8,9))
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(100,1000,5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225,
       230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
       295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355,
       360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415, 420,
       425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485,
       490, 495, 500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550,
       555, 560, 565, 570, 575, 580, 585, 590, 595, 600, 605, 610, 615,
       620, 625, 630, 635, 640, 645, 650, 655, 660, 665, 670, 675, 680,
       685, 690, 695, 700, 705, 710, 715, 720, 725, 730, 735, 740, 745,
       750, 755, 760, 765, 770, 775, 780, 785, 790, 795, 800, 805, 810,
       815, 820, 825, 830, 835, 840, 845, 850, 855, 860, 865, 870, 875,
       880, 885, 890, 895, 900, 905, 910, 915, 920, 925, 930, 935, 940,
       945, 950, 955, 960, 965, 970, 975, 980, 985, 990, 995])

In [11]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [12]:
np.arange(20,31,2)

array([20, 22, 24, 26, 28, 30])

In [13]:
np.random.rand(2,3) # 2행 3열

array([[0.23548339, 0.865102  , 0.62580023],
       [0.94987408, 0.26536903, 0.09044865]])

In [14]:
# all() : 배열의 모든 원소가 조건을 만족하면 True
# any() : 배열에 조건을 만족하는 원소가 있으면 True
ary = np.random.rand(5)
print(ary)
print(np.all(ary>=0.3))
print(np.any(ary>0.7))

[0.13828885 0.90107826 0.03430284 0.51604905 0.19667253]
False
True


In [15]:
arr4 = np.arange(16)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
arr4.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
arr5 = np.arange(100)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
arr5.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
arr5.reshape(1,100)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [20]:
arr5.reshape(2,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [21]:
arr5.reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:
arr5.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [23]:
arr5.reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [24]:
arr5.reshape(50,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [25]:
arr6 = np.arange(16)
arr6.reshape(2,2,4) # 2행 4열이 2개

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr.shape

(10,)

In [28]:
arr.dtype

dtype('int64')

In [29]:
arr.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
x = np.array([1,3,5,6,7])
print(x.mean()) # 평균값 계산

4.4


In [31]:
x = np.array([1,3,5,7,9,11]).reshape(3,2)
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [32]:
y = np.ones([3,4])
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
x = np.array([[1,3,5],[2,4,6]])
print(x[1])
print(x[1].mean())
print(x.mean()) # 전체의 평균
print(x.shape)

[2 4 6]
4.0
3.5
(2, 3)


In [34]:
arr = np.arange(16)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
arr[5]

5

In [37]:
arr[-1]

15

In [38]:
arr[5:8]

array([5, 6, 7])

In [39]:
arr[5] = 100
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [40]:
arr[6:8] = [200,201]
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [41]:
arr2 = np.arange(16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
arr2[1]

array([4, 5, 6, 7])

In [43]:
arr2[1][1] = 100

In [44]:
arr2

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [45]:
scores = [80,90,70,65,85,95,90,80,75,80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [46]:
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [47]:
score_arr[score_arr >= 90]

array([90, 95, 90])

In [48]:
score_arr >= 70

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [49]:
score_arr[score_arr>=70]

array([80, 90, 70, 85, 95, 90, 80, 75, 80])

In [50]:
score_arr[score_arr>=90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

In [51]:
score_arr[score_arr>=80] = 888

In [52]:
score_arr

array([888, 888,  70,  65, 888, 888, 888, 888,  75, 888])

In [53]:
arr2 = np.arange(16).reshape(4,4)

In [54]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
a = np.array([10,20,30,40,50,60,70])
b = a > 50
print(b)

[False False False False False  True  True]


In [56]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1])

[4 5 6]


In [57]:
print(x[:,1])

[2 5 8]


In [58]:
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[:,1]+y[:,1])

[ 5 11 17]


In [59]:
print(x[:,1]+y[:,2])
print(x[:1]+y[:2])

[ 6 12 18]
[[ 3  5  7]
 [ 6  8 10]]


In [60]:
a = np.array([10,20,30,40,50,60,70])
i = [1,3,5]
print(a[i])

[20 40 60]


In [61]:
print(a[i]+x[:])

[[21 42 63]
 [24 45 66]
 [27 48 69]]


In [62]:
print(x[::]+y[::])
print(x[:,:]+y[:,:])

[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]
[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]


In [63]:
# 슬라이싱
list1 = [[1,11],[2,12],[3,13]]
np_ary = np.array(list1)
print(np_ary[:,1])

[11 12 13]


In [64]:
print(np_ary[:,0])

[1 2 3]


In [65]:
print(np_ary[:2,1])

[11 12]


In [66]:
print(np_ary[:2][1])

[ 2 12]


In [67]:
a = np.array([10,20,30,40,50,60,70,80,90])
b = np.array(a[1:6:2])
print('b:',b)

b: [20 40 60]


In [68]:
type(b)

numpy.ndarray

In [69]:
b[1] = 10
print('b:',b)

b: [20 10 60]


In [70]:
print('a:',a)

a: [10 20 30 40 50 60 70 80 90]


In [71]:
arr = a.reshape(3,3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [72]:
arr[0][2]

30

In [73]:
arr[:,2] + 2

array([32, 62, 92])

In [74]:
arr[:,2][1] + 2

62

In [75]:
arr[:,1] * 2

array([ 40, 100, 160])

In [76]:
arr[0][1] * 2

40

In [77]:
arry = np.arange(1,5)

In [78]:
arry

array([1, 2, 3, 4])

In [79]:
arry//2

array([0, 1, 1, 2])

In [80]:
arry/2

array([0.5, 1. , 1.5, 2. ])

In [81]:
arr2 = np.arange(2,6)
arr2

array([2, 3, 4, 5])

In [82]:
arry+arr2

array([3, 5, 7, 9])

In [83]:
arr3 = np.arange(3,13,3)
arr3

array([ 3,  6,  9, 12])

In [84]:
list1 = [1,2,3,4]
list1

[1, 2, 3, 4]

In [85]:
y = list1 * 2

In [86]:
y

[1, 2, 3, 4, 1, 2, 3, 4]

In [87]:
print(list1*2)
print(list1)

[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4]


In [88]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [89]:
arr1 = np.arange(2,6)
arr1

array([2, 3, 4, 5])

In [90]:
# 제곱
np.square(arr)

array([[ 100,  400,  900],
       [1600, 2500, 3600],
       [4900, 6400, 8100]])

In [91]:
# 제곱근(루트)
np.sqrt(arr)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [92]:
# 지수승
np.exp(arr)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26],
       [2.51543867e+30, 5.54062238e+34, 1.22040329e+39]])

In [93]:
# log
np.log(arr)

array([[2.30258509, 2.99573227, 3.40119738],
       [3.68887945, 3.91202301, 4.09434456],
       [4.24849524, 4.38202663, 4.49980967]])

In [100]:
# 합계
np.sum(arr)

10

In [101]:
# 누적합
np.cumsum(arr)

array([ 1,  3,  6, 10])

In [102]:
# 평균
np.mean(arr)

2.5

In [103]:
# 편차
np.var(arr)

1.25

In [104]:
# 표준편차
np.std(arr)

1.118033988749895

In [105]:
# 최소값
np.min(arr)

1

In [106]:
# 최대값
np.max(arr)

4

In [107]:
# 최소값의 인덱스
np.argmin(arr)

0

In [108]:
# 최대값의 인덱스
np.argmax(arr)

3

In [109]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)
print(x*y)
print(x/y)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [110]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [111]:
arr.T  # arr.transpose()와 동일

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [112]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [113]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [114]:
arr3d + 2

array([[[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [115]:
arr3d.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [116]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [117]:
arrd = np.arange(20).reshape(2,2,5)
arrd

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [118]:
arrd.T

array([[[ 0, 10],
        [ 5, 15]],

       [[ 1, 11],
        [ 6, 16]],

       [[ 2, 12],
        [ 7, 17]],

       [[ 3, 13],
        [ 8, 18]],

       [[ 4, 14],
        [ 9, 19]]])

In [119]:
np.save('array',arr)

In [120]:
load_arr = np.load('array.npy')
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])